name: Continuous Delivery
on: 
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        run: echo "Testando Continuous Delivery"

      - name: Upload artefatos
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            **.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: projetozipado
      - name: Display structure of downloaded files
        run: ls -R
